<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

# Financial Theory with Python
**&mdash;A Gentle Introduction**

Dr Yves J Hilpisch | The Python Quants | The AI Machine

http://tpq.io | http://aimachine.io | [@dyjh](http://twitter.com/dyjh)

<img src="https://hilpisch.com/finpy_cover.png" width=30% border=1px align=left>

## Chapter 01 &mdash; Finance and Python

## Approach of the Book

In [1]:
vu = 1.5

In [2]:
vd = 3.75

In [3]:
type(vu)

float

In [4]:
vu + vd

5.25

In [5]:
import numpy as np

In [6]:
v = np.array((vu, vd))

In [7]:
v

array([1.5 , 3.75])

In [8]:
v.dtype

dtype('float64')

In [9]:
v.shape

(2,)

In [10]:
v + v

array([3. , 7.5])

In [11]:
3 * v

array([ 4.5 , 11.25])

In [12]:
S = np.array((20, 5))

In [13]:
K = 15

In [14]:
C = np.maximum(S - K, 0)

In [15]:
C

array([5, 0])

<img src="http://hilpisch.com/tpq_logo.png" alt="The Python Quants" width="35%" align="right" border="0"><br>

<a href="http://tpq.io" target="_blank">http://tpq.io</a> | <a href="http://twitter.com/dyjh" target="_blank">@dyjh</a> | <a href="mailto:training@tpq.io">training@tpq.io</a>